### ISSUE TITLE
What sources did you used ?

### ISSUE THREAD

**Issue by gagantous** [wraithseeker/AniKawaii#1]
Does this web used angular js ? since, idont get any loading gif on the web tab , but i got loading gif at top right corner.

i do know  that you used Ruby on rails, but can you be more specific like, a list of what kind library did you used on this project

what kind of database did you used ?
and did you used your own hosting/server ? or you have to rent/pay server and db for a month ?

thanks in advance

**Comment by gagantous** [comment]
and sorry for my bad english

**Comment by wraithseeker** [comment]
This project doesn't use angularJS but it uses turbolinks to achieve the effect that you described. You can check out what libraries are used in the gemfile of the project

**Comment by gagantous** [comment]
oh thanks, i didn't know that gemfile used for, since i am new on github :)

thanks anyway

**Comment by gagantous** [comment]
ohh so you dont use any db, but you used API  from reddit instead.

i thought they were fetched from your db, but instead you  stored the the data for the gifs first and dan fetched it again
